    language: python # => 1

    python: # => 2

      - "2.7"

    services: # => 3

      - postgresql

    env: # => 4

      -DJANGO=1.11
#    install: # => 5

#      - pip install -r requirements.txt

#    before_script: cd lop

#    script: # => 7

#      - python manage.py runserver 0.0.0.0:8000
