language: python

python:
  - 2.6
  - 2.7

services: postgresql

env:
  - DJANGO=1.11

before_install:
  - export DJANGO_SETTINGS_MODULE=lop.settings
  - export PIP_USE_MIRRORS=true

install:
  - pip install coverage
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet

before_script:
  - echo $USER
  - pwd
  - ls -l /home/travis/build/$USER/lop
  - psql -c "CREATE DATABASE lop;" -U postgres

script:
  - coverage run --source=home manage.py test home
  - python manage.py syncdb --noinput

after_success: coveralls
