language: python

python:

  - 3.6

services: postgresql

env:
  global:
  - DJANGO=2.0.5
  - DB_NAME='lop'
  - DB_USER='lopadmin'
  - DB_PASS='lop'
  - DB_HOST='localhost'

before_install:
  - export DJANGO_SETTINGS_MODULE=lop.settings
  - export PIP_USE_MIRRORS=true

install:
  - pip install coverage
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet

before_script:
  - psql -c "CREATE DATABASE lop;" -U postgres
  - psql -c "CREATE USER lopadmin WITH PASSWORD 'lop';" -U postgres
  - psql -c "ALTER ROLE lopadmin  SET client_encoding TO 'utf8';" -U postgres
  - psql -c "ALTER ROLE lopadmin SET default_transaction_isolation TO 'read committed';" -U postgres
  - psql -c "ALTER ROLE lopadmin SET timezone TO 'UTC';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE lop TO lopadmin;" -U postgres
  - psql -c "ALTER USER lopadmin CREATEDB;" -U postgres

script:
  - cd ./lop/
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test lop
