language: python

python:

  - 2.7

services: postgresql

env:
  - DJANGO=1.11

before_install:
  - export DJANGO_SETTINGS_MODULE=lop.settings
  - export PIP_USE_MIRRORS=true

install:
  - pip install coverage
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet

before_script:
  - psql -c "CREATE DATABASE lop;" -U postgres

script:
  - coverage run --source=lop manage.py test lop
  - cd ./lop/
  - python manage.py runserver

after_success: coveralls
