"""
Django settings for lop project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
print("BASE_DIR"+BASE_DIR)
TEMPLATE_PATH = os.path.join(BASE_DIR, 'lop/templates')
STATIC_PATH = os.path.join(BASE_DIR, 'lop/')
print(TEMPLATE_PATH)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%2^n+y_3%%$wtf4lpn!l+ffnzw6+r_xr=y%s=%s7^hyms!ptnw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# Set login redirect location
LOGIN_REDIRECT_URL = 'index'
#Set Database Info

#DB_NAME = os.environ['DB_NAME']
#DB_USER = os.environ['DB_USER']
#DB_PASS = os.environ['DB_PASS']

print("BASE_DIR:" + BASE_DIR)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
print("MEDIA_ROOT:" + MEDIA_ROOT)
MEDIA_URL = '/media/'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_swagger',
    'api',
    'lop',
    'avatar',
]
for app in INSTALLED_APPS:
    print(app + " is installed")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_PATH],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME' : 'postgres',
        'USER' : 'postgres',
        'HOST' : 'db',
        'PORT' : '5432',
        'TEST': {
            'NAME': 'lop_test',
        },
    }
}


AUTH_PROFILE_MODULE = 'lop.account.UserProfile'

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 600 # set just 10 seconds to test
SESSION_SAVE_EVERY_REQUEST = True

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'lop/static/')
print("STATIC_ROOT" + STATIC_ROOT)
STATICFILES_DIRS = ( os.path.join(BASE_DIR, '/lop/'), )
STATIC_URL = '/static/'
